task: main.c input.o inrnd.c output.o divide.o
	gcc -g -o task main.c input.o inrnd.c output.o divide.o -no-pie
input.o: input.asm
	nasm -f elf64 -g -F dwarf input.asm -l input.lst
output.o: output.asm
	nasm -f elf64 -g -F dwarf output.asm -l output.lst
divide.o: divide.asm
	nasm -f elf64 -g -F dwarf divide.asm -l divide.lst
